### ISSUE TITLE
PyLeapMouse Pointer Goes to Corner

### ISSUE THREAD

**Issue by luis84** [openleap/PyLeapMouse#25]
Hello,

Using PyLeapMouse in Linux Mint (Ubuntu 13.04) when I insert a finger into the frame the mouse will go all the way to the top left corner and sit there, it will not do anything else.

Can anybody comment on the potential cause of this?

**Comment by lium** [comment]
same here.

left button up
Traceback (most recent call last):
  File "/home/ming/code/PyLeapMouse/FingerControl.py", line 51, in on_frame
    self.cursor.scroll(x_scroll, y_scroll)
  File "/home/ming/code/PyLeapMouse/Linux/Mouse.py", line 108, in scroll
    AbsoluteMouseScroll(posx, posy, up)
  File "/home/ming/code/PyLeapMouse/Linux/Mouse.py", line 30, in AbsoluteMouseScroll
    mouse.click(posx, posy, button=5)
  File "/usr/local/lib/python2.7/dist-packages/PyMouse-1.0-py2.7.egg/pymouse/__init__.py", line 44, in click
    self.press(x, y, button)
  File "/usr/local/lib/python2.7/dist-packages/PyMouse-1.0-py2.7.egg/pymouse/unix.py", line 32, in press
    fake_input(display, X.ButtonPress, [None, 1, 3, 2][button])
IndexError: list index out of range
left button up
Traceback (most recent call last):
  File "/home/ming/code/PyLeapMouse/FingerControl.py", line 51, in on_frame
    self.cursor.scroll(x_scroll, y_scroll)
  File "/home/ming/code/PyLeapMouse/Linux/Mouse.py", line 108, in scroll
    AbsoluteMouseScroll(posx, posy, up)
  File "/home/ming/code/PyLeapMouse/Linux/Mouse.py", line 30, in AbsoluteMouseScroll
    mouse.click(posx, posy, button=5)
  File "/usr/local/lib/python2.7/dist-packages/PyMouse-1.0-py2.7.egg/pymouse/__init__.py", line 44, in click
    self.press(x, y, button)
  File "/usr/local/lib/python2.7/dist-packages/PyMouse-1.0-py2.7.egg/pymouse/unix.py", line 32, in press
    fake_input(display, X.ButtonPress, [None, 1, 3, 2][button])
IndexError: list index out of range

**Comment by abondis** [comment]
same thing using ubuntu 14.04 and Leap SDK 2.2.2

**Comment by abondis** [comment]
for those interested this version works for me https://github.com/rpav/PyLeapMouse

**Comment by lium** [comment]
I think the key concern is that everybody is hoping it can work as natural
as possible. However, these drivers are still far from that.

2016-01-08 2:56 GMT+08:00 Aurelien <notifications@github.com>:

> for those interested this version works for me
> https://github.com/rpav/PyLeapMouse
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openleap/PyLeapMouse/issues/25#issuecomment-169773154>
> .
>



-- 

Ming Liu  (Assistant Prof. Dr.)

Robotics and Multiperception Lab  (www.ram-lab.com)
Department of Mechanical and Biomedical Engineering
City University of Hong Kong
Tat Chee Avenue, Kowloon,
Hong Kong

www.intorobot.com

Phone: +852 3442 2308
Mobile: +852 5445 1473
___________________________________
